"""Refresh the public distributions used by the League rank comparison.

Only aggregate rating counts are saved; individual Codeforces profiles are not.
Run with .venv/bin/python scripts/update_rank_distributions.py, then review and
deploy the generated snapshot. Optional input files allow offline reproduction.
"""

import argparse
import json
import re
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

import requests
from bs4 import BeautifulSoup

CF_URL = 'https://codeforces.com/api/user.ratedList?activeOnly=true&includeRetired=false'
LEAGUE_URL = 'https://op.gg/lol/statistics/tiers?region=na'
LEAGUE_NAMES = ['Challenger', 'Grandmaster', 'Master'] + [
    f'{tier} {division}' for tier in ['Diamond', 'Emerald', 'Platinum', 'Gold', 'Silver', 'Bronze', 'Iron']
    for division in ['I', 'II', 'III', 'IV']
]


def cf_counts(payload):
    if payload.get('status') != 'OK' or not payload.get('result'):
        raise ValueError('Codeforces did not return rated users')
    ratings = [user.get('rating') for user in payload['result']]
    if any(type(rating) is not int for rating in ratings):
        raise ValueError('A Codeforces rating is missing or invalid')
    return sorted(Counter(ratings).items())


def league_counts(html):
    soup = BeautifulSoup(html, 'html.parser')
    selected = soup.select_one('#selectChampionRegion option[selected]')
    if selected is None or selected.get('value') != 'na':
        raise ValueError('The League source did not select North America')
    table = next((t for t in soup.select('table') if 'Detailed league stats' in t.get_text()), None)
    if table is None:
        raise ValueError('The League distribution is missing')
    result = []
    cumulative = 0
    for row in table.select('tbody tr'):
        cells = row.find_all(['td', 'th'], recursive=False)
        if len(cells) != 3:
            continue
        name = cells[0].get_text(' ', strip=True)
        name = re.sub(r' [1-4]$', lambda m: ' ' + ['I', 'II', 'III', 'IV'][int(m[0]) - 1], name)
        count_match = re.match(r'([\d,]+)\s*\(', cells[1].get_text(' ', strip=True))
        total_match = re.match(r'([\d,]+)\s*\(', cells[2].get_text(' ', strip=True))
        if not count_match or not total_match:
            raise ValueError('The League source has invalid player counts')
        count = int(count_match[1].replace(',', ''))
        cumulative += count
        if count <= 0 or cumulative != int(total_match[1].replace(',', '')):
            raise ValueError('The League cumulative counts do not agree')
        result.append((name, count))
    if [name for name, _ in result] != LEAGUE_NAMES:
        raise ValueError('League ranks are missing or out of order')
    return result


def download(url):
    response = requests.get(url, timeout=(5, 45))
    response.raise_for_status()
    return response.text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cf-json', type=Path)
    parser.add_argument('--league-html', type=Path)
    parser.add_argument('--date', default=datetime.now(timezone.utc).date().isoformat(),
                        help='UTC capture date, including when importing saved responses')
    args = parser.parse_args()
    datetime.strptime(args.date, '%Y-%m-%d')
    cf = cf_counts(json.loads(args.cf_json.read_text() if args.cf_json else download(CF_URL)))
    league = league_counts(args.league_html.read_text() if args.league_html else download(LEAGUE_URL))
    cf_total = sum(count for _, count in cf)
    league_total = sum(count for _, count in league)
    if cf_total < 1000 or league_total < 100000:
        raise ValueError('Refusing to replace the snapshot with an incomplete distribution')
    metadata = {'date': args.date, 'codeforcesUrl': CF_URL, 'leagueUrl': LEAGUE_URL,
                'codeforcesPlayers': cf_total, 'leaguePlayers': league_total,
                'codeforcesPopulation': 'Active in a rated contest in the past month',
                'leaguePopulation': 'North America Ranked Solo/Duo'}
    text = '// Generated by scripts/update_rank_distributions.py. Aggregate public counts only.\n'
    text += f'export const RANK_DISTRIBUTION_SOURCE = {json.dumps(metadata, indent=2)} as const;\n\n'
    text += 'export const CF_RATING_COUNTS: readonly (readonly [number, number])[] = [\n'
    text += ''.join(f'  [{rating}, {count}],\n' for rating, count in cf) + '];\n\n'
    text += 'export const LEAGUE_RANK_COUNTS: readonly (readonly [string, number])[] = [\n'
    text += ''.join(f'  [{json.dumps(name)}, {count}],\n' for name, count in league) + '];\n'
    output = Path(__file__).resolve().parents[1] / 'pwa-frontend/src/rankDistributions.ts'
    output.write_text(text)
    print(f'Saved {cf_total:,} Codeforces ratings and {league_total:,} League players, dated {args.date}')


if __name__ == '__main__':
    main()
